/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as FindBattleContractJson } from "../gamefi/battle/FindBattle.ral.json";
import { getContractByCodeHash } from "./contracts";
import { MoveReturn, AllStructs } from "./types";

// Custom types for the contract
export namespace FindBattleTypes {
  export type Fields = {
    admin: Address;
    pvp: HexString;
  };

  export type State = ContractState<Fields>;

  export type BattleEvent = ContractEvent<{ who: Address; id: HexString }>;

  export interface CallMethodTable {
    createBattle: {
      params: CallContractParams<{ paca: HexString }>;
      result: CallContractResult<null>;
    };
    upgrade: {
      params: CallContractParams<{ newCode: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createBattle: {
      params: SignExecuteContractMethodParams<{ paca: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    upgrade: {
      params: SignExecuteContractMethodParams<{ newCode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FindBattleInstance,
  FindBattleTypes.Fields
> {
  encodeFields(fields: FindBattleTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { Battle: 0 };
  consts = { Error: { NotAdmin: BigInt("0") } };

  at(address: string): FindBattleInstance {
    return new FindBattleInstance(address);
  }

  tests = {
    createBattle: async (
      params: TestContractParamsWithoutMaps<
        FindBattleTypes.Fields,
        { paca: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "createBattle", params, getContractByCodeHash);
    },
    upgrade: async (
      params: TestContractParamsWithoutMaps<
        FindBattleTypes.Fields,
        { newCode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgrade", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FindBattleTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FindBattle = new Factory(
  Contract.fromJson(
    FindBattleContractJson,
    "",
    "6b200b448476b04263c3503a9546c58e93cdf8984632eef618f3c985bad56dd0",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class FindBattleInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FindBattleTypes.State> {
    return fetchContractState(FindBattle, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBattleEvent(
    options: EventSubscribeOptions<FindBattleTypes.BattleEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FindBattle.contract,
      this,
      options,
      "Battle",
      fromCount
    );
  }

  view = {
    createBattle: async (
      params: FindBattleTypes.CallMethodParams<"createBattle">
    ): Promise<FindBattleTypes.CallMethodResult<"createBattle">> => {
      return callMethod(
        FindBattle,
        this,
        "createBattle",
        params,
        getContractByCodeHash
      );
    },
    upgrade: async (
      params: FindBattleTypes.CallMethodParams<"upgrade">
    ): Promise<FindBattleTypes.CallMethodResult<"upgrade">> => {
      return callMethod(
        FindBattle,
        this,
        "upgrade",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createBattle: async (
      params: FindBattleTypes.SignExecuteMethodParams<"createBattle">
    ): Promise<FindBattleTypes.SignExecuteMethodResult<"createBattle">> => {
      return signExecuteMethod(FindBattle, this, "createBattle", params);
    },
    upgrade: async (
      params: FindBattleTypes.SignExecuteMethodParams<"upgrade">
    ): Promise<FindBattleTypes.SignExecuteMethodResult<"upgrade">> => {
      return signExecuteMethod(FindBattle, this, "upgrade", params);
    },
  };
}
