/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as LoanFactoryTestContractJson } from "../test/LoanFactoryTest.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { DIAOracleValue, PlayerData, AllStructs } from "./types";

// Custom types for the contract
export namespace LoanFactoryTestTypes {
  export type Fields = {
    admin: Address;
    loanTemplate: HexString;
    activeLoans: bigint;
    rate: bigint;
  };

  export type State = ContractState<Fields>;

  export type NewLoanEvent = ContractEvent<{
    contract: HexString;
    tokenRequested: HexString;
    tokenAmount: bigint;
    collateralToken: HexString;
    collateralAmount: bigint;
    interest: bigint;
    duration: bigint;
    who: Address;
  }>;
  export type AcceptedLoanEvent = ContractEvent<{
    contract: HexString;
    who: Address;
  }>;
  export type LoanRemovedEvent = ContractEvent<{
    contract: HexString;
    who: Address;
  }>;
  export type LoanWithdrawEvent = ContractEvent<{
    contract: HexString;
    forfeit: boolean;
    who: Address;
  }>;

  export interface CallMethodTable {
    getRequiredTokens: {
      params: CallContractParams<{
        contractId: HexString;
        withInterest: boolean;
        interestTime: bigint;
      }>;
      result: CallContractResult<[HexString, bigint]>;
    };
    checkTokenAmount: {
      params: CallContractParams<{ priceIn: bigint; commissionRateIn: bigint }>;
      result: CallContractResult<null>;
    };
    createLoan: {
      params: CallContractParams<{
        tokenRequested: HexString;
        tokenAmount: bigint;
        collateralToken: HexString;
        collateralAmount: bigint;
        interest: bigint;
        duration: bigint;
      }>;
      result: CallContractResult<null>;
    };
    accept: {
      params: CallContractParams<{ contractId: HexString; startTime: bigint }>;
      result: CallContractResult<null>;
    };
    cancel: {
      params: CallContractParams<{ contractId: HexString }>;
      result: CallContractResult<null>;
    };
    pay: {
      params: CallContractParams<{
        contractId: HexString;
        interestTime: bigint;
      }>;
      result: CallContractResult<null>;
    };
    forfeit: {
      params: CallContractParams<{
        contractId: HexString;
        forfeitTime: bigint;
      }>;
      result: CallContractResult<null>;
    };
    editRate: {
      params: CallContractParams<{ newRate: bigint }>;
      result: CallContractResult<null>;
    };
    destroyLoanFactory: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    withdrawLoanFactoryFees: {
      params: CallContractParams<{
        who: Address;
        token: HexString;
        amount: bigint;
      }>;
      result: CallContractResult<null>;
    };
    updateLoanFactoryCode: {
      params: CallContractParams<{ newCode: HexString }>;
      result: CallContractResult<null>;
    };
    updateLoanFactoryFields: {
      params: CallContractParams<{
        newCode: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getRequiredTokens: {
      params: SignExecuteContractMethodParams<{
        contractId: HexString;
        withInterest: boolean;
        interestTime: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    checkTokenAmount: {
      params: SignExecuteContractMethodParams<{
        priceIn: bigint;
        commissionRateIn: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    createLoan: {
      params: SignExecuteContractMethodParams<{
        tokenRequested: HexString;
        tokenAmount: bigint;
        collateralToken: HexString;
        collateralAmount: bigint;
        interest: bigint;
        duration: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    accept: {
      params: SignExecuteContractMethodParams<{
        contractId: HexString;
        startTime: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    cancel: {
      params: SignExecuteContractMethodParams<{ contractId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    pay: {
      params: SignExecuteContractMethodParams<{
        contractId: HexString;
        interestTime: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    forfeit: {
      params: SignExecuteContractMethodParams<{
        contractId: HexString;
        forfeitTime: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    editRate: {
      params: SignExecuteContractMethodParams<{ newRate: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    destroyLoanFactory: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdrawLoanFactoryFees: {
      params: SignExecuteContractMethodParams<{
        who: Address;
        token: HexString;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    updateLoanFactoryCode: {
      params: SignExecuteContractMethodParams<{ newCode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    updateLoanFactoryFields: {
      params: SignExecuteContractMethodParams<{
        newCode: HexString;
        immFields: HexString;
        mutFields: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  LoanFactoryTestInstance,
  LoanFactoryTestTypes.Fields
> {
  encodeFields(fields: LoanFactoryTestTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { NewLoan: 0, AcceptedLoan: 1, LoanRemoved: 2, LoanWithdraw: 3 };
  consts = {
    LoanCodes: { NotAdmin: BigInt("0"), TokenSizeTooSmall: BigInt("1") },
  };

  at(address: string): LoanFactoryTestInstance {
    return new LoanFactoryTestInstance(address);
  }

  tests = {
    getRequiredTokens: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { contractId: HexString; withInterest: boolean; interestTime: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, bigint]>> => {
      return testMethod(
        this,
        "getRequiredTokens",
        params,
        getContractByCodeHash
      );
    },
    checkTokenAmount: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { priceIn: bigint; commissionRateIn: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "checkTokenAmount",
        params,
        getContractByCodeHash
      );
    },
    createLoan: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        {
          tokenRequested: HexString;
          tokenAmount: bigint;
          collateralToken: HexString;
          collateralAmount: bigint;
          interest: bigint;
          duration: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "createLoan", params, getContractByCodeHash);
    },
    accept: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { contractId: HexString; startTime: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "accept", params, getContractByCodeHash);
    },
    cancel: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { contractId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "cancel", params, getContractByCodeHash);
    },
    pay: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { contractId: HexString; interestTime: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "pay", params, getContractByCodeHash);
    },
    forfeit: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { contractId: HexString; forfeitTime: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "forfeit", params, getContractByCodeHash);
    },
    editRate: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { newRate: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "editRate", params, getContractByCodeHash);
    },
    destroyLoanFactory: async (
      params: Omit<
        TestContractParamsWithoutMaps<LoanFactoryTestTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "destroyLoanFactory",
        params,
        getContractByCodeHash
      );
    },
    withdrawLoanFactoryFees: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { who: Address; token: HexString; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "withdrawLoanFactoryFees",
        params,
        getContractByCodeHash
      );
    },
    updateLoanFactoryCode: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { newCode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "updateLoanFactoryCode",
        params,
        getContractByCodeHash
      );
    },
    updateLoanFactoryFields: async (
      params: TestContractParamsWithoutMaps<
        LoanFactoryTestTypes.Fields,
        { newCode: HexString; immFields: HexString; mutFields: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "updateLoanFactoryFields",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: LoanFactoryTestTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const LoanFactoryTest = new Factory(
  Contract.fromJson(
    LoanFactoryTestContractJson,
    "",
    "d1119e9a732da9a43cba273b005e2931c3c44ef96b55130bff7ccf3eb4c99e98",
    AllStructs
  )
);
registerContract(LoanFactoryTest);

// Use this class to interact with the blockchain
export class LoanFactoryTestInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<LoanFactoryTestTypes.State> {
    return fetchContractState(LoanFactoryTest, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeNewLoanEvent(
    options: EventSubscribeOptions<LoanFactoryTestTypes.NewLoanEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LoanFactoryTest.contract,
      this,
      options,
      "NewLoan",
      fromCount
    );
  }

  subscribeAcceptedLoanEvent(
    options: EventSubscribeOptions<LoanFactoryTestTypes.AcceptedLoanEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LoanFactoryTest.contract,
      this,
      options,
      "AcceptedLoan",
      fromCount
    );
  }

  subscribeLoanRemovedEvent(
    options: EventSubscribeOptions<LoanFactoryTestTypes.LoanRemovedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LoanFactoryTest.contract,
      this,
      options,
      "LoanRemoved",
      fromCount
    );
  }

  subscribeLoanWithdrawEvent(
    options: EventSubscribeOptions<LoanFactoryTestTypes.LoanWithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LoanFactoryTest.contract,
      this,
      options,
      "LoanWithdraw",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | LoanFactoryTestTypes.NewLoanEvent
      | LoanFactoryTestTypes.AcceptedLoanEvent
      | LoanFactoryTestTypes.LoanRemovedEvent
      | LoanFactoryTestTypes.LoanWithdrawEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      LoanFactoryTest.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    getRequiredTokens: async (
      params: LoanFactoryTestTypes.CallMethodParams<"getRequiredTokens">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"getRequiredTokens">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "getRequiredTokens",
        params,
        getContractByCodeHash
      );
    },
    checkTokenAmount: async (
      params: LoanFactoryTestTypes.CallMethodParams<"checkTokenAmount">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"checkTokenAmount">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "checkTokenAmount",
        params,
        getContractByCodeHash
      );
    },
    createLoan: async (
      params: LoanFactoryTestTypes.CallMethodParams<"createLoan">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"createLoan">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "createLoan",
        params,
        getContractByCodeHash
      );
    },
    accept: async (
      params: LoanFactoryTestTypes.CallMethodParams<"accept">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"accept">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "accept",
        params,
        getContractByCodeHash
      );
    },
    cancel: async (
      params: LoanFactoryTestTypes.CallMethodParams<"cancel">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"cancel">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "cancel",
        params,
        getContractByCodeHash
      );
    },
    pay: async (
      params: LoanFactoryTestTypes.CallMethodParams<"pay">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"pay">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "pay",
        params,
        getContractByCodeHash
      );
    },
    forfeit: async (
      params: LoanFactoryTestTypes.CallMethodParams<"forfeit">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"forfeit">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "forfeit",
        params,
        getContractByCodeHash
      );
    },
    editRate: async (
      params: LoanFactoryTestTypes.CallMethodParams<"editRate">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"editRate">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "editRate",
        params,
        getContractByCodeHash
      );
    },
    destroyLoanFactory: async (
      params?: LoanFactoryTestTypes.CallMethodParams<"destroyLoanFactory">
    ): Promise<LoanFactoryTestTypes.CallMethodResult<"destroyLoanFactory">> => {
      return callMethod(
        LoanFactoryTest,
        this,
        "destroyLoanFactory",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdrawLoanFactoryFees: async (
      params: LoanFactoryTestTypes.CallMethodParams<"withdrawLoanFactoryFees">
    ): Promise<
      LoanFactoryTestTypes.CallMethodResult<"withdrawLoanFactoryFees">
    > => {
      return callMethod(
        LoanFactoryTest,
        this,
        "withdrawLoanFactoryFees",
        params,
        getContractByCodeHash
      );
    },
    updateLoanFactoryCode: async (
      params: LoanFactoryTestTypes.CallMethodParams<"updateLoanFactoryCode">
    ): Promise<
      LoanFactoryTestTypes.CallMethodResult<"updateLoanFactoryCode">
    > => {
      return callMethod(
        LoanFactoryTest,
        this,
        "updateLoanFactoryCode",
        params,
        getContractByCodeHash
      );
    },
    updateLoanFactoryFields: async (
      params: LoanFactoryTestTypes.CallMethodParams<"updateLoanFactoryFields">
    ): Promise<
      LoanFactoryTestTypes.CallMethodResult<"updateLoanFactoryFields">
    > => {
      return callMethod(
        LoanFactoryTest,
        this,
        "updateLoanFactoryFields",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getRequiredTokens: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"getRequiredTokens">
    ): Promise<
      LoanFactoryTestTypes.SignExecuteMethodResult<"getRequiredTokens">
    > => {
      return signExecuteMethod(
        LoanFactoryTest,
        this,
        "getRequiredTokens",
        params
      );
    },
    checkTokenAmount: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"checkTokenAmount">
    ): Promise<
      LoanFactoryTestTypes.SignExecuteMethodResult<"checkTokenAmount">
    > => {
      return signExecuteMethod(
        LoanFactoryTest,
        this,
        "checkTokenAmount",
        params
      );
    },
    createLoan: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"createLoan">
    ): Promise<LoanFactoryTestTypes.SignExecuteMethodResult<"createLoan">> => {
      return signExecuteMethod(LoanFactoryTest, this, "createLoan", params);
    },
    accept: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"accept">
    ): Promise<LoanFactoryTestTypes.SignExecuteMethodResult<"accept">> => {
      return signExecuteMethod(LoanFactoryTest, this, "accept", params);
    },
    cancel: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"cancel">
    ): Promise<LoanFactoryTestTypes.SignExecuteMethodResult<"cancel">> => {
      return signExecuteMethod(LoanFactoryTest, this, "cancel", params);
    },
    pay: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"pay">
    ): Promise<LoanFactoryTestTypes.SignExecuteMethodResult<"pay">> => {
      return signExecuteMethod(LoanFactoryTest, this, "pay", params);
    },
    forfeit: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"forfeit">
    ): Promise<LoanFactoryTestTypes.SignExecuteMethodResult<"forfeit">> => {
      return signExecuteMethod(LoanFactoryTest, this, "forfeit", params);
    },
    editRate: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"editRate">
    ): Promise<LoanFactoryTestTypes.SignExecuteMethodResult<"editRate">> => {
      return signExecuteMethod(LoanFactoryTest, this, "editRate", params);
    },
    destroyLoanFactory: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"destroyLoanFactory">
    ): Promise<
      LoanFactoryTestTypes.SignExecuteMethodResult<"destroyLoanFactory">
    > => {
      return signExecuteMethod(
        LoanFactoryTest,
        this,
        "destroyLoanFactory",
        params
      );
    },
    withdrawLoanFactoryFees: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"withdrawLoanFactoryFees">
    ): Promise<
      LoanFactoryTestTypes.SignExecuteMethodResult<"withdrawLoanFactoryFees">
    > => {
      return signExecuteMethod(
        LoanFactoryTest,
        this,
        "withdrawLoanFactoryFees",
        params
      );
    },
    updateLoanFactoryCode: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"updateLoanFactoryCode">
    ): Promise<
      LoanFactoryTestTypes.SignExecuteMethodResult<"updateLoanFactoryCode">
    > => {
      return signExecuteMethod(
        LoanFactoryTest,
        this,
        "updateLoanFactoryCode",
        params
      );
    },
    updateLoanFactoryFields: async (
      params: LoanFactoryTestTypes.SignExecuteMethodParams<"updateLoanFactoryFields">
    ): Promise<
      LoanFactoryTestTypes.SignExecuteMethodResult<"updateLoanFactoryFields">
    > => {
      return signExecuteMethod(
        LoanFactoryTest,
        this,
        "updateLoanFactoryFields",
        params
      );
    },
  };

  async multicall<Calls extends LoanFactoryTestTypes.MultiCallParams>(
    calls: Calls
  ): Promise<LoanFactoryTestTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends LoanFactoryTestTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<LoanFactoryTestTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | LoanFactoryTestTypes.MultiCallParams
      | LoanFactoryTestTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      LoanFactoryTest,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
