/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as OldNFTPublicSaleCollectionSequentialContractJson } from "../nfts/publicsale/old_nfts/OldNFTPublicSaleCollectionSequential.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  DIAOracleValue,
  PairInfo,
  PlayerData,
  TokenData,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace OldNFTPublicSaleCollectionSequentialTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    nftBaseUri: HexString;
    collectionOwner: Address;
    maxSupply: bigint;
    mintPrice: bigint;
    maxBatchMintSize: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{
    minter: Address;
    fromIndex: bigint;
    mintSize: bigint;
  }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    mint_: {
      params: CallContractParams<{ minter: Address; index: bigint }>;
      result: CallContractResult<HexString>;
    };
    mint: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    mintBatch: {
      params: CallContractParams<{ size: bigint }>;
      result: CallContractResult<HexString>;
    };
    withdraw: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getNFTUri: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    getMintPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint_: {
      params: SignExecuteContractMethodParams<{
        minter: Address;
        index: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    mintBatch: {
      params: SignExecuteContractMethodParams<{ size: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getNFTUri: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getMintPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  OldNFTPublicSaleCollectionSequentialInstance,
  OldNFTPublicSaleCollectionSequentialTypes.Fields
> {
  encodeFields(fields: OldNFTPublicSaleCollectionSequentialTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { Mint: 0 };
  consts = {
    PublicSaleErrorCodes: { IncorrectTokenIndex: BigInt("0") },
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("2"),
      InvalidMintBatchSize: BigInt("3"),
      InsufficientNumOfUnminted: BigInt("4"),
      NFTNotFound: BigInt("0"),
      CollectionOwnerAllowedOnly: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): OldNFTPublicSaleCollectionSequentialInstance {
    return new OldNFTPublicSaleCollectionSequentialInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          OldNFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          OldNFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        OldNFTPublicSaleCollectionSequentialTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        OldNFTPublicSaleCollectionSequentialTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    mint_: async (
      params: TestContractParamsWithoutMaps<
        OldNFTPublicSaleCollectionSequentialTypes.Fields,
        { minter: Address; index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint_", params, getContractByCodeHash);
    },
    mint: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          OldNFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    mintBatch: async (
      params: TestContractParamsWithoutMaps<
        OldNFTPublicSaleCollectionSequentialTypes.Fields,
        { size: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mintBatch", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        OldNFTPublicSaleCollectionSequentialTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    getNFTUri: async (
      params: TestContractParamsWithoutMaps<
        OldNFTPublicSaleCollectionSequentialTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getNFTUri", params, getContractByCodeHash);
    },
    getMintPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          OldNFTPublicSaleCollectionSequentialTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMintPrice", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: OldNFTPublicSaleCollectionSequentialTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const OldNFTPublicSaleCollectionSequential = new Factory(
  Contract.fromJson(
    OldNFTPublicSaleCollectionSequentialContractJson,
    "",
    "106b681abeea8979a2cb57584c47f07b3d029e87301fb85b7f9dddb65c86877b",
    AllStructs
  )
);
registerContract(OldNFTPublicSaleCollectionSequential);

// Use this class to interact with the blockchain
export class OldNFTPublicSaleCollectionSequentialInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<OldNFTPublicSaleCollectionSequentialTypes.State> {
    return fetchContractState(OldNFTPublicSaleCollectionSequential, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<OldNFTPublicSaleCollectionSequentialTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      OldNFTPublicSaleCollectionSequential.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  view = {
    getCollectionUri: async (
      params?: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"totalSupply">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"totalSupply">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"nftByIndex">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"nftByIndex">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"validateNFT">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"validateNFT">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    mint_: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"mint_">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"mint_">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "mint_",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params?: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"mint">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"mint">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "mint",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    mintBatch: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"mintBatch">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"mintBatch">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "mintBatch",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"withdraw">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"withdraw">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    getNFTUri: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"getNFTUri">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"getNFTUri">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "getNFTUri",
        params,
        getContractByCodeHash
      );
    },
    getMintPrice: async (
      params?: OldNFTPublicSaleCollectionSequentialTypes.CallMethodParams<"getMintPrice">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.CallMethodResult<"getMintPrice">
    > => {
      return callMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "getMintPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "totalSupply",
        params
      );
    },
    nftByIndex: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"nftByIndex">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "nftByIndex",
        params
      );
    },
    validateNFT: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "validateNFT",
        params
      );
    },
    mint_: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"mint_">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"mint_">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "mint_",
        params
      );
    },
    mint: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"mint">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"mint">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "mint",
        params
      );
    },
    mintBatch: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"mintBatch">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"mintBatch">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "mintBatch",
        params
      );
    },
    withdraw: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"withdraw">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "withdraw",
        params
      );
    },
    getNFTUri: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"getNFTUri">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"getNFTUri">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "getNFTUri",
        params
      );
    },
    getMintPrice: async (
      params: OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodParams<"getMintPrice">
    ): Promise<
      OldNFTPublicSaleCollectionSequentialTypes.SignExecuteMethodResult<"getMintPrice">
    > => {
      return signExecuteMethod(
        OldNFTPublicSaleCollectionSequential,
        this,
        "getMintPrice",
        params
      );
    },
  };

  async multicall<
    Calls extends OldNFTPublicSaleCollectionSequentialTypes.MultiCallParams
  >(
    calls: Calls
  ): Promise<OldNFTPublicSaleCollectionSequentialTypes.MultiCallResults<Calls>>;
  async multicall<
    Callss extends OldNFTPublicSaleCollectionSequentialTypes.MultiCallParams[]
  >(
    callss: Narrow<Callss>
  ): Promise<
    OldNFTPublicSaleCollectionSequentialTypes.MulticallReturnType<Callss>
  >;
  async multicall<
    Callss extends
      | OldNFTPublicSaleCollectionSequentialTypes.MultiCallParams
      | OldNFTPublicSaleCollectionSequentialTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      OldNFTPublicSaleCollectionSequential,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
