/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as PlayerBaseContractJson } from "../gamefi/PlayerBase.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace PlayerBaseTypes {
  export type Fields = {
    collectionOwner: Address;
    collectionUri: HexString;
    gameContract: HexString;
    totalSupply: bigint;
    baseuri: HexString;
    playerContractId: HexString;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{
    minter: Address;
    fromIndex: bigint;
    contract: HexString;
  }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; index: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdrawNonNative: {
      params: CallContractParams<{
        to: Address;
        token: HexString;
        amount: bigint;
      }>;
      result: CallContractResult<null>;
    };
    mint: {
      params: CallContractParams<{ tokenSelected: HexString; index: bigint }>;
      result: CallContractResult<null>;
    };
    editCollectionUri: {
      params: CallContractParams<{ newCollectionUri: HexString }>;
      result: CallContractResult<null>;
    };
    updatePlayerBase: {
      params: CallContractParams<{ newCode: HexString }>;
      result: CallContractResult<null>;
    };
    updatePlayerBaseFields: {
      params: CallContractParams<{
        newCode: HexString;
        newImmFieldsEncoded: HexString;
        newMutFieldsEncoded: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        index: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawNonNative: {
      params: SignExecuteContractMethodParams<{
        to: Address;
        token: HexString;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{
        tokenSelected: HexString;
        index: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    editCollectionUri: {
      params: SignExecuteContractMethodParams<{ newCollectionUri: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    updatePlayerBase: {
      params: SignExecuteContractMethodParams<{ newCode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    updatePlayerBaseFields: {
      params: SignExecuteContractMethodParams<{
        newCode: HexString;
        newImmFieldsEncoded: HexString;
        newMutFieldsEncoded: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  PlayerBaseInstance,
  PlayerBaseTypes.Fields
> {
  encodeFields(fields: PlayerBaseTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Mint: 0 };
  consts = {
    ErrorCodes: {
      NFTNotFound: BigInt("0"),
      CollectionOwnerAllowedOnly: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): PlayerBaseInstance {
    return new PlayerBaseInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<PlayerBaseTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<PlayerBaseTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        { nftId: HexString; index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    withdrawNonNative: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        { to: Address; token: HexString; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "withdrawNonNative",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        { tokenSelected: HexString; index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    editCollectionUri: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        { newCollectionUri: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "editCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    updatePlayerBase: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        { newCode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "updatePlayerBase",
        params,
        getContractByCodeHash
      );
    },
    updatePlayerBaseFields: async (
      params: TestContractParamsWithoutMaps<
        PlayerBaseTypes.Fields,
        {
          newCode: HexString;
          newImmFieldsEncoded: HexString;
          newMutFieldsEncoded: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "updatePlayerBaseFields",
        params,
        getContractByCodeHash
      );
    },
  };
}

// Use this object to test and deploy the contract
export const PlayerBase = new Factory(
  Contract.fromJson(
    PlayerBaseContractJson,
    "",
    "b48eaa750e0ca54a57bf00c1b505fa617ef5d07461188399ad6003c2d21e9d85",
    []
  )
);

// Use this class to interact with the blockchain
export class PlayerBaseInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PlayerBaseTypes.State> {
    return fetchContractState(PlayerBase, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<PlayerBaseTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PlayerBase.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  view = {
    getCollectionUri: async (
      params?: PlayerBaseTypes.CallMethodParams<"getCollectionUri">
    ): Promise<PlayerBaseTypes.CallMethodResult<"getCollectionUri">> => {
      return callMethod(
        PlayerBase,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: PlayerBaseTypes.CallMethodParams<"totalSupply">
    ): Promise<PlayerBaseTypes.CallMethodResult<"totalSupply">> => {
      return callMethod(
        PlayerBase,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: PlayerBaseTypes.CallMethodParams<"nftByIndex">
    ): Promise<PlayerBaseTypes.CallMethodResult<"nftByIndex">> => {
      return callMethod(
        PlayerBase,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: PlayerBaseTypes.CallMethodParams<"validateNFT">
    ): Promise<PlayerBaseTypes.CallMethodResult<"validateNFT">> => {
      return callMethod(
        PlayerBase,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: PlayerBaseTypes.CallMethodParams<"withdraw">
    ): Promise<PlayerBaseTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        PlayerBase,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    withdrawNonNative: async (
      params: PlayerBaseTypes.CallMethodParams<"withdrawNonNative">
    ): Promise<PlayerBaseTypes.CallMethodResult<"withdrawNonNative">> => {
      return callMethod(
        PlayerBase,
        this,
        "withdrawNonNative",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: PlayerBaseTypes.CallMethodParams<"mint">
    ): Promise<PlayerBaseTypes.CallMethodResult<"mint">> => {
      return callMethod(
        PlayerBase,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
    editCollectionUri: async (
      params: PlayerBaseTypes.CallMethodParams<"editCollectionUri">
    ): Promise<PlayerBaseTypes.CallMethodResult<"editCollectionUri">> => {
      return callMethod(
        PlayerBase,
        this,
        "editCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    updatePlayerBase: async (
      params: PlayerBaseTypes.CallMethodParams<"updatePlayerBase">
    ): Promise<PlayerBaseTypes.CallMethodResult<"updatePlayerBase">> => {
      return callMethod(
        PlayerBase,
        this,
        "updatePlayerBase",
        params,
        getContractByCodeHash
      );
    },
    updatePlayerBaseFields: async (
      params: PlayerBaseTypes.CallMethodParams<"updatePlayerBaseFields">
    ): Promise<PlayerBaseTypes.CallMethodResult<"updatePlayerBaseFields">> => {
      return callMethod(
        PlayerBase,
        this,
        "updatePlayerBaseFields",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<PlayerBaseTypes.SignExecuteMethodResult<"getCollectionUri">> => {
      return signExecuteMethod(PlayerBase, this, "getCollectionUri", params);
    },
    totalSupply: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<PlayerBaseTypes.SignExecuteMethodResult<"totalSupply">> => {
      return signExecuteMethod(PlayerBase, this, "totalSupply", params);
    },
    nftByIndex: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<PlayerBaseTypes.SignExecuteMethodResult<"nftByIndex">> => {
      return signExecuteMethod(PlayerBase, this, "nftByIndex", params);
    },
    validateNFT: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<PlayerBaseTypes.SignExecuteMethodResult<"validateNFT">> => {
      return signExecuteMethod(PlayerBase, this, "validateNFT", params);
    },
    withdraw: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<PlayerBaseTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(PlayerBase, this, "withdraw", params);
    },
    withdrawNonNative: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"withdrawNonNative">
    ): Promise<
      PlayerBaseTypes.SignExecuteMethodResult<"withdrawNonNative">
    > => {
      return signExecuteMethod(PlayerBase, this, "withdrawNonNative", params);
    },
    mint: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"mint">
    ): Promise<PlayerBaseTypes.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(PlayerBase, this, "mint", params);
    },
    editCollectionUri: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"editCollectionUri">
    ): Promise<
      PlayerBaseTypes.SignExecuteMethodResult<"editCollectionUri">
    > => {
      return signExecuteMethod(PlayerBase, this, "editCollectionUri", params);
    },
    updatePlayerBase: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"updatePlayerBase">
    ): Promise<PlayerBaseTypes.SignExecuteMethodResult<"updatePlayerBase">> => {
      return signExecuteMethod(PlayerBase, this, "updatePlayerBase", params);
    },
    updatePlayerBaseFields: async (
      params: PlayerBaseTypes.SignExecuteMethodParams<"updatePlayerBaseFields">
    ): Promise<
      PlayerBaseTypes.SignExecuteMethodResult<"updatePlayerBaseFields">
    > => {
      return signExecuteMethod(
        PlayerBase,
        this,
        "updatePlayerBaseFields",
        params
      );
    },
  };

  async multicall<Callss extends PlayerBaseTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<PlayerBaseTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      PlayerBase,
      this,
      callss,
      getContractByCodeHash
    )) as PlayerBaseTypes.MulticallReturnType<Callss>;
  }
}
