/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as PowerMoveContractJson } from "../gamefi/moves/PowerMove.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { DIAOracleValue, MoveReturn, AllStructs } from "./types";

// Custom types for the contract
export namespace PowerMoveTypes {
  export type Fields = {
    nftIndex: bigint;
    tokenUri: HexString;
    collectionId: HexString;
    power: bigint;
    accuracy: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint]>;
    };
    getNFTIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    editUri: {
      params: CallContractParams<{ newUri: HexString }>;
      result: CallContractResult<null>;
    };
    performMove: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<MoveReturn>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getTokenUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCollectionIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNFTIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    editUri: {
      params: SignExecuteContractMethodParams<{ newUri: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    performMove: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  PowerMoveInstance,
  PowerMoveTypes.Fields
> {
  encodeFields(fields: PowerMoveTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  consts = { ErrorCodes: { NotCalledFromCollection: BigInt("0") } };

  at(address: string): PowerMoveInstance {
    return new PowerMoveInstance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<PowerMoveTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenUri", params, getContractByCodeHash);
    },
    getCollectionIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<PowerMoveTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, bigint]>> => {
      return testMethod(
        this,
        "getCollectionIndex",
        params,
        getContractByCodeHash
      );
    },
    getNFTIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<PowerMoveTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getNFTIndex", params, getContractByCodeHash);
    },
    editUri: async (
      params: TestContractParamsWithoutMaps<
        PowerMoveTypes.Fields,
        { newUri: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "editUri", params, getContractByCodeHash);
    },
    performMove: async (
      params: Omit<
        TestContractParamsWithoutMaps<PowerMoveTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<MoveReturn>> => {
      return testMethod(this, "performMove", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: PowerMoveTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const PowerMove = new Factory(
  Contract.fromJson(
    PowerMoveContractJson,
    "",
    "e4b8b71d6658f7d964db2e2dad368ee721f5182cc7a4df7dd2b2bf71c97f8bb4",
    AllStructs
  )
);
registerContract(PowerMove);

// Use this class to interact with the blockchain
export class PowerMoveInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PowerMoveTypes.State> {
    return fetchContractState(PowerMove, this);
  }

  view = {
    getTokenUri: async (
      params?: PowerMoveTypes.CallMethodParams<"getTokenUri">
    ): Promise<PowerMoveTypes.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        PowerMove,
        this,
        "getTokenUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCollectionIndex: async (
      params?: PowerMoveTypes.CallMethodParams<"getCollectionIndex">
    ): Promise<PowerMoveTypes.CallMethodResult<"getCollectionIndex">> => {
      return callMethod(
        PowerMove,
        this,
        "getCollectionIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNFTIndex: async (
      params?: PowerMoveTypes.CallMethodParams<"getNFTIndex">
    ): Promise<PowerMoveTypes.CallMethodResult<"getNFTIndex">> => {
      return callMethod(
        PowerMove,
        this,
        "getNFTIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    editUri: async (
      params: PowerMoveTypes.CallMethodParams<"editUri">
    ): Promise<PowerMoveTypes.CallMethodResult<"editUri">> => {
      return callMethod(
        PowerMove,
        this,
        "editUri",
        params,
        getContractByCodeHash
      );
    },
    performMove: async (
      params?: PowerMoveTypes.CallMethodParams<"performMove">
    ): Promise<PowerMoveTypes.CallMethodResult<"performMove">> => {
      return callMethod(
        PowerMove,
        this,
        "performMove",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getTokenUri: async (
      params: PowerMoveTypes.SignExecuteMethodParams<"getTokenUri">
    ): Promise<PowerMoveTypes.SignExecuteMethodResult<"getTokenUri">> => {
      return signExecuteMethod(PowerMove, this, "getTokenUri", params);
    },
    getCollectionIndex: async (
      params: PowerMoveTypes.SignExecuteMethodParams<"getCollectionIndex">
    ): Promise<
      PowerMoveTypes.SignExecuteMethodResult<"getCollectionIndex">
    > => {
      return signExecuteMethod(PowerMove, this, "getCollectionIndex", params);
    },
    getNFTIndex: async (
      params: PowerMoveTypes.SignExecuteMethodParams<"getNFTIndex">
    ): Promise<PowerMoveTypes.SignExecuteMethodResult<"getNFTIndex">> => {
      return signExecuteMethod(PowerMove, this, "getNFTIndex", params);
    },
    editUri: async (
      params: PowerMoveTypes.SignExecuteMethodParams<"editUri">
    ): Promise<PowerMoveTypes.SignExecuteMethodResult<"editUri">> => {
      return signExecuteMethod(PowerMove, this, "editUri", params);
    },
    performMove: async (
      params: PowerMoveTypes.SignExecuteMethodParams<"performMove">
    ): Promise<PowerMoveTypes.SignExecuteMethodResult<"performMove">> => {
      return signExecuteMethod(PowerMove, this, "performMove", params);
    },
  };

  async multicall<Calls extends PowerMoveTypes.MultiCallParams>(
    calls: Calls
  ): Promise<PowerMoveTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends PowerMoveTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<PowerMoveTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | PowerMoveTypes.MultiCallParams
      | PowerMoveTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      PowerMove,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
