/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as SwapContractJson } from "../swaps/Swap.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace SwapTypes {
  export type Fields = {
    sell: bigint;
    selltoken: HexString;
    buy: bigint;
    buytoken: HexString;
    owner: Address;
  };

  export type State = ContractState<Fields>;

  export type SwapCompleteEvent = ContractEvent<{
    type: bigint;
    id: HexString;
  }>;
  export type CancelEvent = ContractEvent<{ type: bigint; id: HexString }>;

  export interface CallMethodTable {
    getSell: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getSellToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getBuy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getBuyToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getSellBuyRatio: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<SwapInstance, SwapTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as SwapTypes.Fields;
  }

  eventIndex = { SwapComplete: 0, Cancel: 1 };

  at(address: string): SwapInstance {
    return new SwapInstance(address);
  }

  tests = {
    getSell: async (
      params: Omit<TestContractParams<SwapTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getSell", params);
    },
    getSellToken: async (
      params: Omit<TestContractParams<SwapTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSellToken", params);
    },
    getBuy: async (
      params: Omit<TestContractParams<SwapTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getBuy", params);
    },
    getBuyToken: async (
      params: Omit<TestContractParams<SwapTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getBuyToken", params);
    },
    getSellBuyRatio: async (
      params: Omit<TestContractParams<SwapTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getSellBuyRatio", params);
    },
    confirmswap: async (
      params: Omit<TestContractParams<SwapTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "confirmswap", params);
    },
    cancelswap: async (
      params: Omit<TestContractParams<SwapTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "cancelswap", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Swap = new Factory(
  Contract.fromJson(
    SwapContractJson,
    "",
    "894de413005867ad18bc1032eab7eb84976244cdc03de1ff500ce8233fd9dc5a"
  )
);

// Use this class to interact with the blockchain
export class SwapInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SwapTypes.State> {
    return fetchContractState(Swap, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeSwapCompleteEvent(
    options: EventSubscribeOptions<SwapTypes.SwapCompleteEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Swap.contract,
      this,
      options,
      "SwapComplete",
      fromCount
    );
  }

  subscribeCancelEvent(
    options: EventSubscribeOptions<SwapTypes.CancelEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Swap.contract,
      this,
      options,
      "Cancel",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      SwapTypes.SwapCompleteEvent | SwapTypes.CancelEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Swap.contract, this, options, fromCount);
  }

  methods = {
    getSell: async (
      params?: SwapTypes.CallMethodParams<"getSell">
    ): Promise<SwapTypes.CallMethodResult<"getSell">> => {
      return callMethod(
        Swap,
        this,
        "getSell",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSellToken: async (
      params?: SwapTypes.CallMethodParams<"getSellToken">
    ): Promise<SwapTypes.CallMethodResult<"getSellToken">> => {
      return callMethod(
        Swap,
        this,
        "getSellToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getBuy: async (
      params?: SwapTypes.CallMethodParams<"getBuy">
    ): Promise<SwapTypes.CallMethodResult<"getBuy">> => {
      return callMethod(
        Swap,
        this,
        "getBuy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getBuyToken: async (
      params?: SwapTypes.CallMethodParams<"getBuyToken">
    ): Promise<SwapTypes.CallMethodResult<"getBuyToken">> => {
      return callMethod(
        Swap,
        this,
        "getBuyToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSellBuyRatio: async (
      params?: SwapTypes.CallMethodParams<"getSellBuyRatio">
    ): Promise<SwapTypes.CallMethodResult<"getSellBuyRatio">> => {
      return callMethod(
        Swap,
        this,
        "getSellBuyRatio",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends SwapTypes.MultiCallParams>(
    calls: Calls
  ): Promise<SwapTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Swap,
      this,
      calls,
      getContractByCodeHash
    )) as SwapTypes.MultiCallResults<Calls>;
  }
}
