/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Address, HexString, Val, Struct } from "@alephium/web3";
import { default as allStructsJson } from "../structs.ral.json";
export const AllStructs = allStructsJson.map((json) => Struct.fromJson(json));
export interface DIAOracleValue extends Record<string, Val> {
  value: bigint;
  timestamp: bigint;
}
export interface DIARandomValue extends Record<string, Val> {
  randomness: HexString;
  signature: HexString;
  round: bigint;
}
export interface PlayerData extends Record<string, Val> {
  nft: HexString;
  xp: bigint;
  hp: bigint;
  atk: bigint;
  def: bigint;
  speed: bigint;
  levels: [bigint, bigint, bigint, bigint];
  cooldown: bigint;
}
