/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as CreateTokenContractJson } from "../CreateToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace CreateTokenTypes {
  export type Fields = {
    token: HexString;
    owner: Address;
    alphfee: bigint;
    pacafee: bigint;
    contract: HexString;
  };

  export type State = ContractState<Fields>;

  export type DestroyEvent = ContractEvent<{ user: Address }>;
  export type CreateTokenEvent = ContractEvent<{
    user: Address;
    contract: HexString;
  }>;

  export interface CallMethodTable {
    getTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getAlphFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getPacaFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    buildtoken: {
      params: CallContractParams<{
        symbol: HexString;
        name: HexString;
        decimals: bigint;
        tokenTotal: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    buildtokenpaca: {
      params: CallContractParams<{
        symbol: HexString;
        name: HexString;
        decimals: bigint;
        tokenTotal: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  CreateTokenInstance,
  CreateTokenTypes.Fields
> {
  eventIndex = { Destroy: 0, CreateToken: 1 };
  consts = { ErrorCodes: { InvalidCaller: BigInt(1) } };

  at(address: string): CreateTokenInstance {
    return new CreateTokenInstance(address);
  }

  tests = {
    getTokenId: async (
      params: Omit<
        TestContractParams<CreateTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getTokenId", params);
    },
    getAlphFee: async (
      params: Omit<
        TestContractParams<CreateTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getAlphFee", params);
    },
    getPacaFee: async (
      params: Omit<
        TestContractParams<CreateTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getPacaFee", params);
    },
    changeAlph: async (
      params: TestContractParams<CreateTokenTypes.Fields, { fee: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "changeAlph", params);
    },
    changePaca: async (
      params: TestContractParams<CreateTokenTypes.Fields, { fee: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "changePaca", params);
    },
    buildtoken: async (
      params: TestContractParams<
        CreateTokenTypes.Fields,
        {
          symbol: HexString;
          name: HexString;
          decimals: bigint;
          tokenTotal: bigint;
        }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "buildtoken", params);
    },
    buildtokenpaca: async (
      params: TestContractParams<
        CreateTokenTypes.Fields,
        {
          symbol: HexString;
          name: HexString;
          decimals: bigint;
          tokenTotal: bigint;
        }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "buildtokenpaca", params);
    },
    destroycreator: async (
      params: Omit<
        TestContractParams<CreateTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroycreator", params);
    },
  };
}

// Use this object to test and deploy the contract
export const CreateToken = new Factory(
  Contract.fromJson(
    CreateTokenContractJson,
    "",
    "d649d2d6685ff0f3ae60595f377dc54fc3fc3731d83cf1e13bf72ffe5741129d"
  )
);

// Use this class to interact with the blockchain
export class CreateTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CreateTokenTypes.State> {
    return fetchContractState(CreateToken, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeDestroyEvent(
    options: EventSubscribeOptions<CreateTokenTypes.DestroyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CreateToken.contract,
      this,
      options,
      "Destroy",
      fromCount
    );
  }

  subscribeCreateTokenEvent(
    options: EventSubscribeOptions<CreateTokenTypes.CreateTokenEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      CreateToken.contract,
      this,
      options,
      "CreateToken",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      CreateTokenTypes.DestroyEvent | CreateTokenTypes.CreateTokenEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      CreateToken.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    getTokenId: async (
      params?: CreateTokenTypes.CallMethodParams<"getTokenId">
    ): Promise<CreateTokenTypes.CallMethodResult<"getTokenId">> => {
      return callMethod(
        CreateToken,
        this,
        "getTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAlphFee: async (
      params?: CreateTokenTypes.CallMethodParams<"getAlphFee">
    ): Promise<CreateTokenTypes.CallMethodResult<"getAlphFee">> => {
      return callMethod(
        CreateToken,
        this,
        "getAlphFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getPacaFee: async (
      params?: CreateTokenTypes.CallMethodParams<"getPacaFee">
    ): Promise<CreateTokenTypes.CallMethodResult<"getPacaFee">> => {
      return callMethod(
        CreateToken,
        this,
        "getPacaFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    buildtoken: async (
      params: CreateTokenTypes.CallMethodParams<"buildtoken">
    ): Promise<CreateTokenTypes.CallMethodResult<"buildtoken">> => {
      return callMethod(
        CreateToken,
        this,
        "buildtoken",
        params,
        getContractByCodeHash
      );
    },
    buildtokenpaca: async (
      params: CreateTokenTypes.CallMethodParams<"buildtokenpaca">
    ): Promise<CreateTokenTypes.CallMethodResult<"buildtokenpaca">> => {
      return callMethod(
        CreateToken,
        this,
        "buildtokenpaca",
        params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends CreateTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CreateTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      CreateToken,
      this,
      calls,
      getContractByCodeHash
    )) as CreateTokenTypes.MultiCallResults<Calls>;
  }
}
